In [12]:
import numpy as np
import pandas as pd

In [13]:
from sklearn import metrics

In [14]:
c = "Cat"
d = "dog"
f = "fox"

In [15]:
# true values

y_true = [c, c, c, c, c, c, c, d, d, d, d, d, d, d, f, f, f, f, f, f, f]

# predicted values

y_pred = [c, c, c, c, d, f, c, d, d, f, d, d, c, d, f, f, c, f, d, d, f]

In [17]:
# print the confusion metrics

print(metrics.confusion_matrix(y_true, y_pred))

[[5 1 1]
 [1 5 1]
 [1 2 4]]


In [23]:
print(metrics.classification_report(y_true, y_pred, digits = 3))

              precision    recall  f1-score   support

         Cat      0.714     0.714     0.714         7
         dog      0.625     0.714     0.667         7
         fox      0.667     0.571     0.615         7

    accuracy                          0.667        21
   macro avg      0.669     0.667     0.665        21
weighted avg      0.669     0.667     0.665        21

